# Generated by Django 3.2.5 on 2021-08-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='uploads/images/phones_image.jpg', upload_to='uploads/images'),
        ),
    ]
