# Generated by Django 3.2.5 on 2021-08-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='uploads/images/phone_image.jpg', upload_to='uploads/images'),
        ),
    ]
