# Generated by Django 3.2.5 on 2021-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(max_length=280),
        ),
    ]
