# Generated by Django 3.2.5 on 2021-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210821_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(max_length=1000),
        ),
    ]
